# Site
title:              13bit
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.13bit.io" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: pages
  values:
    title: 13bit consulting
    description: 13bit consulting is an iOS development shop based in San Francisco
    layout: page

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

collections:
  - projects

# Comments
disqus_shortname:   default

# personal
location:           San Francisco CA
phone:              415-734-7235
email:              tyler@13bit

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
